# Generated by Django 3.2.8 on 2021-11-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DirEnvio', '0002_alter_direccionenvio_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionenvio',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
