# Generated by Django 3.2.8 on 2021-10-26 01:48

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_cart_products'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cartproduct',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
