# Generated by Django 3.2.8 on 2021-11-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_codigo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodigo',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
    ]
