# Generated by Django 3.2.8 on 2021-11-08 13:54

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('promo_codigo', '0002_alter_promocodigo_descuento'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='promocodigo',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
