# Generated by Django 3.2.8 on 2021-11-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo_codigo', '0003_alter_promocodigo_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='promocodigo',
            managers=[
            ],
        ),
    ]
